### ISSUE TITLE
示例运行错误

### ISSUE THREAD

**Issue by huangwei2013** [windosx/face-engine#20] opened 2022-03-29 06:10 UTC
求问

1、linux centos7.6
2、sdk包，Linux_x64_V3.0 (https://arcfacepackages.blob.core.chinacloudapi.cn/arcface-packages/sdk/arcface/linux/ArcSoft_ArcFace_Linux_x64_V3.0.zip)
3、代码，如readme 

错误信息
`
[root@k8s-master face]# go run test.go 
# github.com/windosx/face-engine/v4
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetActiveDeviceInfo':
/tmp/go-build/cgo-gcc-prolog:173: undefined reference to `ASFGetActiveDeviceInfo'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetFaceLandMark':
/tmp/go-build/cgo-gcc-prolog:248: undefined reference to `ASFGetFaceLandMark'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFGetMask':
/tmp/go-build/cgo-gcc-prolog:324: undefined reference to `ASFGetMask'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFImageQualityDetect':
/tmp/go-build/cgo-gcc-prolog:370: undefined reference to `ASFImageQualityDetect'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFOfflineActivation':
/tmp/go-build/cgo-gcc-prolog:410: undefined reference to `ASFOfflineActivation'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFSetFaceShelterParam':
/tmp/go-build/cgo-gcc-prolog:520: undefined reference to `ASFSetFaceShelterParam'
/tmp/go-build3806936039/b035/_x002.o: In function `_cgo_a391bd3f5a30_Cfunc_ASFUpdateFaceData':
/tmp/go-build/cgo-gcc-prolog:581: undefined reference to `ASFUpdateFaceData'
collect2: error: ld returned 1 exit status`

**Comment by windosx** [comment] 2022-03-29 07:31
Duplicate of #19

**Closed as completed by windosx** 2022-03-29 07:31 UTC

**Comment by windosx** [comment] 2022-03-29 07:33
请使用v3版本
`go get -u -d github.com/windosx/face-engine/v3`
